services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi
    networks:
      - app-network
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: streamlit
    networks:
      - app-network
    expose:
      - "8501"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - fastapi
      - streamlit

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local